### PR TITLE
update to Zig 0.11

### PR DESCRIPTION
**Pull request by nektro**

### CODE REVIEW

**Comment by glyh** [comment]
addPackagePath is not present in zig 0.11:
```
/home/lyh/Documents/CS/compiler/yula/yula/build.zig:35:8: error: no field or member function named 'addPackagePath' in 'Build.Step.Compile'
    exe.addPackagePath("pcre", "vendor/libpcre.zig/src/main.zig");
    ~~~^~~~~~~~~~~~~~~
/home/lyh/.zvm/0.11.0/lib/std/Build/Step/Compile.zig:1:1: note: struct declared here
const builtin = @import("builtin");
^~~~~
referenced by:
    runBuild__anon_7159: /home/lyh/.zvm/0.11.0/lib/std/Build.zig:1638:27
    remaining reference traces hidden; use '-freference-trace' to see all reference traces

```

**Comment by nektro** [comment]
I admit I only updated the library part of the code and not the build.zig

**Comment by glyh** [comment]
I'm willing to help, so I fork your fork and commit on it?

**Comment by kivikakk** [comment]
I've pulled in the difference of @mattnite's #12 as 101d81c, and we have a `flake.nix` now too. Thank you all!

**Pull request merged**
